const IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;
const MODULE = /^[A-Za-z_][A-Za-z0-9_.-]*$/;

export function generateBindingArtifact(spec, target) {
  const normalized = normalizeBindingSpec(spec);
  switch (target) {
    case 'c': return generateC(normalized);
    case 'cpp': return generateCpp(normalized);
    case 'python': return generatePython(normalized);
    case 'java': return generateJava(normalized);
    case 'ruby': return generateRuby(normalized);
    case 'php': return generatePhp(normalized);
    case 'perl': return generatePerl(normalized);
    case 'javascript': return generateJavaScript(normalized);
    case 'typescript': return generateTypeScript(normalized);
    case 'wasm': return generateWasmManifest(normalized);
    default: throw new Error(`unsupported binding target: ${target}`);
  }
}

export function normalizeBindingSpec(spec) {
  if (!spec || typeof spec !== 'object' || !MODULE.test(spec.name ?? '') || !Array.isArray(spec.functions)) {
    throw new TypeError('binding spec requires a valid name and functions[]');
  }
  const seen = new Set();
  const functions = spec.functions.map((fn) => {
    if (!fn || !IDENTIFIER.test(fn.name ?? '') || seen.has(fn.name)) throw new TypeError(`invalid or duplicate binding function: ${fn?.name ?? '<missing>'}`);
    seen.add(fn.name);
    const paramSeen = new Set();
    const parameters = (fn.parameters ?? []).map((parameter, index) => {
      const normalized = typeof parameter === 'string' ? { name: parameter, type: 'any' } : parameter;
      if (!IDENTIFIER.test(normalized?.name ?? '') || paramSeen.has(normalized.name)) throw new TypeError(`invalid or duplicate parameter in ${fn.name}: ${normalized?.name ?? index}`);
      paramSeen.add(normalized.name);
      return { name: normalized.name, type: normalizeType(normalized.type ?? 'any'), optional: Boolean(normalized.optional) };
    });
    const required = parameters.filter((parameter) => !parameter.optional).length;
    const firstOptional = parameters.findIndex((parameter) => parameter.optional);
    if (firstOptional >= 0 && parameters.slice(firstOptional).some((parameter) => !parameter.optional)) throw new TypeError(`optional parameters must be trailing in ${fn.name}`);
    return {
      name: fn.name,
      parameters,
      returns: normalizeType(fn.returns ?? 'any'),
      async: fn.async !== false,
      required,
      arity: parameters.length,
      doc: typeof fn.doc === 'string' ? fn.doc : null
    };
  });
  return Object.freeze({ name: spec.name, functions, version: spec.version ?? 1 });
}

function normalizeType(type) {
  if (typeof type !== 'string' || !type.trim()) throw new TypeError('binding type must be a non-empty string');
  const value = type.trim();
  const allowed = new Set(['any','void','null','boolean','integer','float','number','string','bytes','list','map','handle']);
  if (allowed.has(value)) return value;
  if (/^list<(.+)>$/.test(value) || /^map<(.+)>$/.test(value) || /^nullable<(.+)>$/.test(value)) return value;
  throw new TypeError(`unsupported Plasma binding type: ${value}`);
}

function generateC(spec) {
  const guard = `PLASMA_BINDING_${spec.name.replace(/[^A-Za-z0-9]/g, '_').toUpperCase()}_H`;
  const moduleLiteral = cString(spec.name);
  const lines = [
    '/* Generated by Plasma. Do not edit by hand. */',
    `#ifndef ${guard}`,
    `#define ${guard}`,
    '#include <stddef.h>',
    '',
    'typedef int (*plasma_invoke_fn)(',
    '  void *context,',
    '  const char *module_name,',
    '  const char *member_name,',
    '  const char *args_json,',
    '  char **result_json,',
    '  char **error_json',
    ');',
    '',
    'typedef struct plasma_transport {',
    '  void *context;',
    '  plasma_invoke_fn invoke;',
    '} plasma_transport;',
    ''
  ];
  for (const fn of spec.functions) {
    lines.push(`static inline int plasma_${cIdentifier(spec.name)}_${fn.name}(plasma_transport *transport, const char *args_json, char **result_json, char **error_json) {`);
    lines.push('  if (transport == NULL || transport->invoke == NULL || args_json == NULL || result_json == NULL || error_json == NULL) return -1;');
    lines.push(`  return transport->invoke(transport->context, ${moduleLiteral}, ${cString(fn.name)}, args_json, result_json, error_json);`);
    lines.push('}', '');
  }
  lines.push(`#endif /* ${guard} */`, '');
  return lines.join('\n');
}

function generateCpp(spec) {
  const className = `${pascal(spec.name)}Plasma`;
  const methods = spec.functions.map((fn) => `  std::string ${fn.name}(std::string_view args_json) const { return transport_.invoke(${cppString(spec.name)}, ${cppString(fn.name)}, args_json); }`).join('\n');
  return `// Generated by Plasma. Do not edit by hand.\n#pragma once\n#include <string>\n#include <string_view>\n#include <stdexcept>\n\nnamespace plasma {\nclass Transport {\npublic:\n  virtual ~Transport() = default;\n  virtual std::string invoke(std::string_view module_name, std::string_view member_name, std::string_view args_json) const = 0;\n};\n\nclass ${className} {\npublic:\n  explicit ${className}(const Transport& transport) : transport_(transport) {}\n${methods}\nprivate:\n  const Transport& transport_;\n};\n}\n`;
}

function generatePython(spec) {
  const className = pascal(spec.name);
  const methods = spec.functions.map((fn) => {
    const params = fn.parameters.map((p) => `${p.name}${p.optional ? '=None' : ''}`).join(', ');
    const names = fn.parameters.map((p) => p.name).join(', ');
    const prefix = params ? `, ${params}` : '';
    return `    def ${fn.name}(self${prefix}):\n        return self._transport.invoke(${pyString(spec.name)}, ${pyString(fn.name)}, [${names}])`;
  }).join('\n\n');
  return `# Generated by Plasma. Do not edit by hand.\nclass ${className}:\n    def __init__(self, transport):\n        if not hasattr(transport, "invoke"):\n            raise TypeError("Plasma transport must expose invoke(module, member, args)")\n        self._transport = transport\n\n${methods || '    pass'}\n`;
}

function generateJava(spec) {
  const className = `${pascal(spec.name)}Plasma`;
  const methods = spec.functions.map((fn) => {
    const params = fn.parameters.map((p) => `Object ${p.name}`).join(', ');
    const args = fn.parameters.map((p) => p.name).join(', ');
    return `  public Object ${fn.name}(${params}) throws Exception {\n    return transport.invoke(${javaString(spec.name)}, ${javaString(fn.name)}, new Object[]{${args}});\n  }`;
  }).join('\n\n');
  return `// Generated by Plasma. Do not edit by hand.\npublic final class ${className} {\n  public interface Transport {\n    Object invoke(String moduleName, String memberName, Object[] args) throws Exception;\n  }\n\n  private final Transport transport;\n\n  public ${className}(Transport transport) {\n    if (transport == null) throw new IllegalArgumentException("Plasma transport is required");\n    this.transport = transport;\n  }\n\n${methods}\n}\n`;
}

function generateRuby(spec) {
  const methods = spec.functions.map((fn) => {
    const params = fn.parameters.map((p) => `${p.name}${p.optional ? ' = nil' : ''}`).join(', ');
    const args = fn.parameters.map((p) => p.name).join(', ');
    return `  def ${fn.name}(${params})\n    @transport.call(${rubyString(spec.name)}, ${rubyString(fn.name)}, [${args}])\n  end`;
  }).join('\n\n');
  return `# Generated by Plasma. Do not edit by hand.\nclass ${pascal(spec.name)}Plasma\n  def initialize(transport)\n    raise ArgumentError, 'Plasma transport must respond to call' unless transport.respond_to?(:call)\n    @transport = transport\n  end\n\n${methods}\nend\n`;
}

function generatePhp(spec) {
  const methods = spec.functions.map((fn) => {
    const params = fn.parameters.map((p) => `$${p.name}${p.optional ? ' = null' : ''}`).join(', ');
    const args = fn.parameters.map((p) => `$${p.name}`).join(', ');
    return `    public function ${fn.name}(${params}) {\n        return ($this->transport)(${phpString(spec.name)}, ${phpString(fn.name)}, [${args}]);\n    }`;
  }).join('\n\n');
  return `<?php\n// Generated by Plasma. Do not edit by hand.\nfinal class ${pascal(spec.name)}Plasma {\n    private $transport;\n\n    public function __construct(callable $transport) {\n        $this->transport = $transport;\n    }\n\n${methods}\n}\n`;
}

function generatePerl(spec) {
  const methods = spec.functions.map((fn) => {
    const argNames = fn.parameters.map((p) => `$${p.name}`).join(', ');
    const array = fn.parameters.map((p) => `$${p.name}`).join(', ');
    return `sub ${fn.name} {\n  my ($self${argNames ? `, ${argNames}` : ''}) = @_;\n  return $self->{transport}->(${perlString(spec.name)}, ${perlString(fn.name)}, [${array}]);\n}`;
  }).join('\n\n');
  return `# Generated by Plasma. Do not edit by hand.\npackage ${pascal(spec.name)}Plasma;\nuse strict;\nuse warnings;\n\nsub new {\n  my ($class, $transport) = @_;\n  die 'Plasma transport must be a CODE reference' unless ref($transport) eq 'CODE';\n  return bless { transport => $transport }, $class;\n}\n\n${methods}\n\n1;\n`;
}

function generateJavaScript(spec) {
  const methods = spec.functions.map((fn) => {
    const params = fn.parameters.map((p) => p.name).join(', ');
    const args = fn.parameters.map((p) => p.name).join(', ');
    return `  async ${fn.name}(${params}) { return await this.transport.invoke(${JSON.stringify(spec.name)}, ${JSON.stringify(fn.name)}, [${args}]); }`;
  }).join('\n');
  return `// Generated by Plasma. Do not edit by hand.\nexport class ${pascal(spec.name)}Plasma {\n  constructor(transport) { if (!transport || typeof transport.invoke !== 'function') throw new TypeError('Plasma transport must expose invoke()'); this.transport = transport; }\n${methods}\n}\n`;
}

function generateTypeScript(spec) {
  const methods = spec.functions.map((fn) => {
    const params = fn.parameters.map((p) => `${p.name}${p.optional ? '?' : ''}: ${tsType(p.type)}`).join(', ');
    return `  ${fn.name}(${params}): Promise<${tsType(fn.returns)}>;`;
  }).join('\n');
  const impl = spec.functions.map((fn) => {
    const params = fn.parameters.map((p) => `${p.name}${p.optional ? '?' : ''}: ${tsType(p.type)}`).join(', ');
    const args = fn.parameters.map((p) => p.name).join(', ');
    return `  async ${fn.name}(${params}): Promise<${tsType(fn.returns)}> { return await this.transport.invoke(${JSON.stringify(spec.name)}, ${JSON.stringify(fn.name)}, [${args}]) as ${tsType(fn.returns)}; }`;
  }).join('\n');
  return `// Generated by Plasma. Do not edit by hand.\nexport interface PlasmaTransport { invoke(moduleName: string, memberName: string, args: unknown[]): Promise<unknown>; }\nexport interface ${pascal(spec.name)}Api {\n${methods}\n}\nexport class ${pascal(spec.name)}Plasma implements ${pascal(spec.name)}Api {\n  constructor(private readonly transport: PlasmaTransport) {}\n${impl}\n}\n`;
}

function generateWasmManifest(spec) {
  return JSON.stringify({
    protocol: 'plasma-wasm/1',
    module: spec.name,
    version: spec.version,
    imports: spec.functions.map((fn) => ({ name: fn.name, parameters: fn.parameters, returns: fn.returns, async: fn.async }))
  }, null, 2) + '\n';
}

function tsType(type) {
  if (type === 'void') return 'void';
  if (type === 'null') return 'null';
  if (type === 'boolean') return 'boolean';
  if (['integer','float','number'].includes(type)) return 'number';
  if (type === 'string') return 'string';
  if (type === 'bytes') return 'Uint8Array';
  if (type === 'list') return 'unknown[]';
  if (type === 'map') return 'Record<string, unknown>';
  if (type === 'handle') return '{ type: "handle"; id: string }';
  const list = type.match(/^list<(.+)>$/); if (list) return `${tsType(list[1])}[]`;
  const map = type.match(/^map<(.+)>$/); if (map) return `Record<string, ${tsType(map[1])}>`;
  const nullable = type.match(/^nullable<(.+)>$/); if (nullable) return `${tsType(nullable[1])} | null`;
  return 'unknown';
}

function pascal(value) { return value.replace(/(^|[-_.\s]+)([A-Za-z0-9])/g, (_, __, char) => char.toUpperCase()).replace(/[^A-Za-z0-9_$]/g, ''); }
function cIdentifier(value) { return value.replace(/[^A-Za-z0-9_]/g, '_'); }
function cString(value) { return JSON.stringify(value); }
function cppString(value) { return JSON.stringify(value); }
function pyString(value) { return JSON.stringify(value); }
function javaString(value) { return JSON.stringify(value); }
function rubyString(value) { return JSON.stringify(value); }
function phpString(value) { return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`; }
function perlString(value) { return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`; }
